### ISSUE TITLE
sorl thumbnail

### ISSUE THREAD

**Issue by VladimirPal** [ppetrid/yawd-elfinder#23]
Hello!
sorl thumbnail doesn't work with yawd-elfinder. Is there any way to get around the issue?

**Comment by ghost** [comment]
Hello, can you please describe me the problem and the steps to reproduce it? I'm willing to investigate this asap since we have also used sorl-thumbnail in the past and might also need it in the future.

**Comment by VladimirPal** [comment]
sorl thumbnail trying to find image in wrong path

``` python
    image = ElfinderField(optionset='image')
```

``` javascript
{% load thumbnail %}

{% thumbnail item.image "100x100" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
{% endthumbnail %}
```

No such file or directory: u'/path_to_my_project/media/llffim_ZGljdG9waG9uZS1idWcucG5n'

**Comment by ghost** [comment]
since `item.image` is an `ElfinderField`, you should do:

`{% thumbnail item.image.url "100x100" as im %}` instead of `{% thumbnail item.image "100x100" as im %}`

Please tell me if this fixes it for you, for more info see this section of the yawd-elfinder documentation:
http://yawd-elfinder.readthedocs.org/en/latest/usage.html#django-templates

**Comment by VladimirPal** [comment]
Attempted access to '/media/images/my_image.png' denied.

**Comment by ghost** [comment]
sorry you are right, I see that sorl-thumbnail needs the absolute path instead of the url. I'll work on this as soon as possible, this fix must make it to the upcoming yawd-elfinder release this week.

**Comment by VladimirPal** [comment]
Great, I'll wait.

**Comment by ghost** [comment]
This turns out to by a problem originating from sorl-thumbnail path detection algorithm. Since in some cases (like when using the default yawd-elfinder optionsets) the image url is relative, sorl thinks the argument is a file path instead of a url. To solve this create a custom filter like this (tested with sorl-thumbnail 11.12):

@register.filter('fullurl')
def fullurl(value):
    return 'http://localhost:8000%s' % value

and then in the template code

{% thumbnail item.image.url|fullurl "100x100" as im %}

Of course you could optimize the filter for dynamically retrieving the current domain (if you use the django sites framework for example), the above is mostly for demonstration purposes. I don't think we should change something in yawd-elfinder, especially since we support multiple drivers that could return either relative or absolute urls. Hopefully this workaround is sufficient for you, for more info please see also 
this related issue http://stackoverflow.com/questions/7490684/using-static-images-with-sorl-thumbnail and the sorl-thumbnail documentation on how it resolves the image path http://sorl-thumbnail.readthedocs.org/en/latest/template.html#source
