### ISSUE TITLE
Elfinder and not staff members

### ISSUE THREAD

**Issue by Bolik** [ppetrid/yawd-elfinder#26]
@method_decorator(staff_member_required) doesn't allow dispatch queries for non staff-members

**Comment by ghost** [comment]
I moved the decorator to the url registration level. So to allow access to non-staff members, now you should register the urls like this:

urlpatterns = patterns('',
      ...
      url(r'^elfinder/yawd-connector/(?P<optionset>.+)/(?P<start_path>.+)/$',
      ElfinderConnectorView.as_view(),
      name='yawdElfinderConnectorView'),
      ...
   )

..instead of 

   urlpatterns = patterns('',
      ...
      url(r'^elfinder/', include('elfinder.urls')),
      ...
   )

However this is still a temporary solution. We must take this issue into consideration for #6 and include user-level permissions to the upcoming signal-based permission system.
Is this working for you as it is right now?

**Comment by Bolik** [comment]
Yes, it works now. Thank you
